#!/bin/bash

IMAGE_NAME='bupt1987/php'
NGINX_DOCKER_NAME='bupt1987-nginx'
PHP_DOCKER_NAME='bupt1987-php'
MONGO_DOCKER_NAME='bupt1987-mongo'
MYSQL_DOCKER_NAME='bupt1987-mysql'
MEMCACHED_DOCKER_NAME='bupt1987-memcached'
WWW_DIR='/www'

if [ -z "$1" ]; then
	echo 'params is error, for example: docker-shell start|restart|stop|install fpm|nginx|memcache|mongo|mysql'
	exit
fi

if [ "$1" != 'start' ] && [ "$1" != 'restart' ] && [ "$1" != 'stop' ] && [ "$1" != 'uninstall' ] && [ "$1" != 'install' ]; then
	echo 'params is error, for example: docker-shell start|restart|stop|install'
	exit
fi

if [ "$1" == 'install' ]; then
	#安装mongo
	docker ps -a | grep -q ${MONGO_DOCKER_NAME} && ( docker stop ${MONGO_DOCKER_NAME} ; docker rm ${MONGO_DOCKER_NAME} )
	docker run \
		--name ${MONGO_DOCKER_NAME} \
		-d \
		mongo:latest --storageEngine wiredTiger

	#安装mysql
	docker ps -a | grep -q ${MYSQL_DOCKER_NAME} && ( docker stop ${MYSQL_DOCKER_NAME} ; docker rm ${MYSQL_DOCKER_NAME} )
	docker run \
	 	--name ${MYSQL_DOCKER_NAME} \
	 	-e MYSQL_ROOT_PASSWORD=123456 \
	 	-d mysql:latest

	#安装memcached
	docker ps -a | grep -q ${MEMCACHED_DOCKER_NAME} && ( docker stop ${MEMCACHED_DOCKER_NAME} ; docker rm ${MEMCACHED_DOCKER_NAME} )
	docker run \
		--name ${MEMCACHED_DOCKER_NAME} \
		-d \
		memcached:latest

	#安装fpm
	docker ps -a | grep -q ${PHP_DOCKER_NAME} && ( docker stop ${PHP_DOCKER_NAME} ; docker rm ${PHP_DOCKER_NAME} )
	docker run \
		--name ${PHP_DOCKER_NAME} \
		--link ${MONGO_DOCKER_NAME}:mongo \
		--link ${MYSQL_DOCKER_NAME}:mysql \
		--link ${MEMCACHED_DOCKER_NAME}:memcached \
		-v ${WWW_DIR}:/www \
		-v ${WWW_DIR}/logs/php:/var/log/php/ \
		-d \
		${IMAGE_NAME}:latest

	#安装nginx
	docker ps -a | grep -q ${NGINX_DOCKER_NAME} && ( docker stop ${NGINX_DOCKER_NAME} ; docker rm ${NGINX_DOCKER_NAME} )
	docker run \
		--name ${NGINX_DOCKER_NAME} \
		--link ${PHP_DOCKER_NAME}:php \
		-p 443:443 \
		-p 80:80 \
		-v ${WWW_DIR}:/www \
		-v ${WWW_DIR}/nginx/sites-enabled:/etc/nginx/sites-enabled \
		-v ${WWW_DIR}/nginx/ssl:/etc/nginx/ssl \
		-d \
		nginx:latest

	exit
fi


case $2 in
	'fpm' )
		docker $1 ${PHP_DOCKER_NAME}
	;;
	'nginx' )
		docker $1 ${NGINX_DOCKER_NAME}
	;;
	'memcached' )
		docker $1 ${MEMCACHED_DOCKER_NAME}
	;;
	'mongo' )
		docker $1 ${MONGO_DOCKER_NAME}
	;;
	'mysql' )
		docker $1 ${MYSQL_DOCKER_NAME}
	;;
	* )
		#mongo
		docker $1 ${MONGO_DOCKER_NAME}
		#mysql
		docker $1 ${MYSQL_DOCKER_NAME}
		#memcache
		docker $1 ${MEMCACHED_DOCKER_NAME}
		#fpm
		docker $1 ${PHP_DOCKER_NAME}
		#nginx
		docker $1 ${NGINX_DOCKER_NAME}
	;;
esac
